### ISSUE TITLE
Issue with certain bins

### ISSUE THREAD

**Issue by vrou1995** [valdeanda/mebs#1]
Hi,

I'm just running the standard function but for some reason some of my bins work just fine while others produce this error:

bin.9.permissive.fa-proteins.faaUse of uninitialized value in concatenation (.) or string at mebs.pl line 288.
# ERROR : invalid value for fragment size ()
# ERROR: failed to generate attempt2//bin.9.permissive.fa-proteins.faa.sulfur.score
        NAUse of uninitialized value in concatenation (.) or string at mebs.pl line 288.
# ERROR : invalid value for fragment size ()
# ERROR: failed to generate attempt2//bin.9.permissive.fa-proteins.faa.carbon.score
        NAUse of uninitialized value in concatenation (.) or string at mebs.pl line 288.
# ERROR : invalid value for fragment size ()
# ERROR: failed to generate attempt2//bin.9.permissive.fa-proteins.faa.oxygen.score
        NAUse of uninitialized value in concatenation (.) or string at mebs.pl line 288.
# ERROR : invalid value for fragment size ()
# ERROR: failed to generate attempt2//bin.9.permissive.fa-proteins.faa.iron.score
        NAUse of uninitialized value in concatenation (.) or string at mebs.pl line 288.
# ERROR : invalid value for fragment size ()
# ERROR: failed to generate attempt2//bin.9.permissive.fa-proteins.faa.nitrogen.score
        NA

Any idea of how I could solve this? Thanks for putting together this lovely piece of software!

**Comment by brunocontrerasmoreira** [comment]
@valdeanda , it looks like a script is waiting for a fragment size, which should be an integer if I recall, and is not getting it?

**Comment by valdeanda** [comment]
Thanks for letting us know about this issue vrou1995, 
I'm sorry for not putting the updated version of the readme, but It's going to be ready soon. 
About your issue. How are you running mebs.pl?

-First, make sure that you are located within the same directory to run the script mebs.pl. Your input directory can be in another location and your redirect the path. 
- @brunocontrerasmoreira  is right. If you are using bins (MAGs), make sure that you are specifying mebs.pl  -input (your directory) -type (genomes), I don't recommend you to use the -metagenomic option for bins since your mags are going to be larger scaffolds than the metagenomic sequences. 
-Are you running the test genomes directory to see how that works?  The header of the fasta sequences should be an issue, but check if the headers of the ones that didn't work are different.  

Let us know if that works. 
Val
